version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_home:/var/jenkins_home
      # If you need Docker inside Jenkins, uncomment the following line:
      # - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home: {}
